# Generated by Django 4.2.23 on 2025-08-12 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_starter',
            field=models.BooleanField(default=False),
        ),
    ]
