# Generated by Django 4.2.23 on 2025-08-06 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopitem',
            name='item',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='ShopItem',
        ),
    ]
