# Generated by Django 4.2.23 on 2025-08-12 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_app', '0002_item_is_starter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='image_url',
        ),
        migrations.AddField(
            model_name='item',
            name='armor_class',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='damage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='healing',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='rarity',
            field=models.CharField(blank=True, default='common', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='source',
            field=models.CharField(blank=True, default='api', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True, default='No description available.', null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='effect',
            field=models.CharField(blank=True, default='No special effect.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(default='Unknown Item', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='stock',
            field=models.IntegerField(default=1),
        ),
    ]
