# Generated by Django 4.2.23 on 2025-08-17 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_app', '0003_remove_item_image_url_item_armor_class_item_damage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='effect',
        ),
        migrations.RemoveField(
            model_name='item',
            name='item_type',
        ),
        migrations.RemoveField(
            model_name='item',
            name='source',
        ),
        migrations.AddField(
            model_name='item',
            name='cost_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='cost_unit',
            field=models.CharField(default='gp', max_length=2),
        ),
        migrations.AddField(
            model_name='item',
            name='item_category',
            field=models.CharField(default='misc', max_length=50),
        ),
    ]
