# Generated by Django 4.2.23 on 2025-08-26 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_app', '0004_remove_item_effect_remove_item_item_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=10),
        ),
    ]
