# Generated by Django 4.2.23 on 2025-08-07 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('player_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('base_health', models.IntegerField(default=100)),
                ('base_damage', models.IntegerField(default=10)),
                ('element_type', models.CharField(choices=[('fire', 'Fire'), ('water', 'Water'), ('normal', 'Normal'), ('air', 'Air')], default='normal', max_length=50)),
                ('image_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Encounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monster_level', models.IntegerField(default=1)),
                ('outcome', models.CharField(choices=[('victory', 'Victory'), ('defeat', 'Defeat'), ('flee', 'Flee')], default='defeat', max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('monster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encounters', to='monster_app.monster')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encounters', to='player_app.player')),
            ],
        ),
    ]
