# Generated by Django 4.2.23 on 2025-08-06 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Monster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('base_health', models.IntegerField(default=100)),
                ('base_damage', models.IntegerField(default=10)),
                ('element_type', models.CharField(choices=[('fire', 'Fire'), ('water', 'Water'), ('normal', 'Normal'), ('air', 'Air')], default='normal', max_length=50)),
                ('image_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
