# Generated by Django 4.2.23 on 2025-08-17 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monster_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monster',
            old_name='base_damage',
            new_name='armor',
        ),
        migrations.RenameField(
            model_name='monster',
            old_name='base_health',
            new_name='health',
        ),
        migrations.RemoveField(
            model_name='monster',
            name='element_type',
        ),
        migrations.AddField(
            model_name='monster',
            name='damage',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='monster',
            name='passive_perception',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='monster',
            name='type',
            field=models.CharField(default='unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='monster',
            name='xp',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='monster_level',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='monster',
            name='image_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
