# Generated by Django 4.2.23 on 2025-08-06 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monster_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Monster',
        ),
    ]
