# Generated by Django 4.2.23 on 2025-08-18 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monster_app', '0002_rename_base_damage_monster_armor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monster',
            name='challenge_rating',
            field=models.FloatField(default=0),
        ),
    ]
