# Generated by Django 4.2.23 on 2025-08-06 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('monster_app', '0003_initial'),
        ('player_app', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='encounter',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encounters', to='player_app.player'),
        ),
    ]
