# Generated by Django 4.2.23 on 2025-08-09 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='item_name',
            new_name='item',
        ),
    ]
