# Generated by Django 4.2.23 on 2025-08-06 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transation',
            name='item',
        ),
        migrations.RemoveField(
            model_name='transation',
            name='player',
        ),
        migrations.DeleteModel(
            name='Inventory',
        ),
        migrations.DeleteModel(
            name='Player',
        ),
        migrations.DeleteModel(
            name='Transation',
        ),
    ]
