# Generated by Django 4.2.23 on 2025-08-09 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_app', '0002_rename_item_name_inventory_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='user',
            new_name='user_account',
        ),
        migrations.AddField(
            model_name='player',
            name='player_class',
            field=models.CharField(default='Adventurer', max_length=50),
        ),
    ]
