# Generated by Django 4.2.23 on 2025-08-30 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('character_app', '0002_initial'),
        ('quest_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerquest',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character_quests', to='character_app.character'),
        ),
    ]
